version: "3"

services:
  user:
    build: ./user-identity-service
    ports:
      - "8081:8081"

  menu:
    build: ./menu-catalog-service
    ports:
      - "8082:8082"

  order:
    build: ./order-management-service
    ports:
      - "8083:8083"
    depends_on:
      - menu
      - payment

  payment:
    build: ./payment-service
    ports:
      - "8084:8084"
    environment:
      - MONGO_URI=mongodb://mongo-payment:27017/payment-service
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - USER_SERVICE_URL=https://user-identity-service.onrender.com
      - ORDER_SERVICE_URL=https://order-service-production-5615.up.railway.app
      - NODE_ENV=production
    depends_on:
      - mongo-payment

  mongo-payment:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - payment-data:/data/db

volumes:
  payment-data:
